name: remedy_mate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2   # or latest version
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  go_router: ^16.2.1
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  flutter_gen: ^5.11.0
  dartz: ^0.10.1
  bloc: ^9.0.0
  internet_connection_checker: ^3.0.1
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.0
  build_runner: ^2.7.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/mock/
    - assets/
  fonts:
    - family: NotoSansEthiopic
      fonts:
        - asset: assets/fonts/NotoSansEthiopic-VariableFont_wdth,wght.ttf
        # Add other weights and styles if needed
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
