name: remedy_mate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  flutter_gen: ^5.9.0   # <- downgrade
  dartz: ^0.10.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  internet_connection_checker: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0   # <-- fixed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.3.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
