name: Flutter CI/CD

on:
  push:
    branches:
      - dev
      - main
      - 'features/*'
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    # This sets the working directory for ALL subsequent steps in this job
    # which is cleaner than adding `cd remedy_mate` to every single step.
    defaults:
      run:
        working-directory: remedy_mate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK (only for pushes)
        if: github.event_name == 'push'
        run: flutter build apk --debug